### ISSUE TITLE
点击功能都是闪退

### ISSUE THREAD

**Issue by SpiderYtt** [qunat/Pythonocc-CAD#5]
点击功能都是闪退，debug发现因为没有识别到self.parent.Displayshape_core.canva._display.register_select_callback(self.clicked_callback)中的Displayshape_core导致闪退。找不到这个函数啊宽哥

**Comment by SpiderYtt** [comment]
Traceback (most recent call last):
  File "C:\BrepCAD\BrepCAD\Win64\manufacture\manufacturing.py", line 639, in func
    self.show_Blank = self.parent.Displayshape_core.canva._display.DisplayShape(self.Blank, transparency=0.5,
AttributeError: 'Mywindown' object has no attribute 'Displayshape_core'

**Comment by qunat** [comment]
抱歉，因为之前写的不够完美，我最近在重构中。你可以找到早一点的版本。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月30日(周二) 下午4:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [qunat/Pythonocc-CAD] 点击功能都是闪退 (Issue #5)




 
Traceback (most recent call last):
 File "C:\BrepCAD\BrepCAD\Win64\manufacture\manufacturing.py", line 639, in func
 self.show_Blank = self.parent.Displayshape_core.canva._display.DisplayShape(self.Blank, transparency=0.5,
 AttributeError: 'Mywindown' object has no attribute 'Displayshape_core'

**Comment by SpiderYtt** [comment]
> 抱歉，因为之前写的不够完美，我最近在重构中。你可以找到早一点的版本。
> […](#)
> ---原始邮件--- 发件人： ***@***.***> 发送时间: 2024年7月30日(周二) 下午4:15 收件人： ***@***.***>; 抄送： ***@***.***>; 主题： Re： [qunat/Pythonocc-CAD] 点击功能都是闪退 （Issue #5） 回溯（最近一次调用最后一次）： 文件“C：\BrepCAD\BrepCAD\Win64\manufacture\manufacturing.py”，第 639 行，在 func 中 self.show_Blank = self.parent.Displayshape_core.canva._display。DisplayShape（自身。空白，透明度=0.5， AttributeError：“Mywindown”对象没有属性“Displayshape_core” — 直接回复此邮件，在GitHub上查看，或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ID： ***@***.***>

下载了老版本也是一样。请问缺少Displayshape_core这个问题，是还需要下载什么库吗，已下载occ7.4/pyqt5/python3.7

**Comment by SpiderYtt** [comment]
> 抱歉，因为之前写的不够完美，我最近在重构中。你可以找到早一点的版本。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月30日(周二) 下午4:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [qunat/Pythonocc-CAD] 点击功能都是闪退 (Issue #5) Traceback (most recent call last): File "C:\BrepCAD\BrepCAD\Win64\manufacture\manufacturing.py", line 639, in func self.show_Blank = self.parent.Displayshape_core.canva._display.DisplayShape(self.Blank, transparency=0.5, AttributeError: 'Mywindown' object has no attribute 'Displayshape_core' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

宽哥，这个Displayshape_core是你自定义的类还是导入的库文件
